# Generated by Django 4.0.2 on 2022-06-11 20:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dc6ecphjr/image/upload/v1654980533/blank-profile-picture_jitpja.png', max_length=255),
        ),
    ]
