# Generated by Django 4.0.2 on 2022-06-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
    ]
