# Generated by Django 4.0.2 on 2022-06-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
